### ISSUE TITLE
installation confusion

### ISSUE THREAD

**Issue by N6REJ** [geerlingguy/macos-virtualbox-vm#30]
Do you create the vbox on the pc or mac?  I have a amd fx-8350 on sabertooth gen 2 motherboard.

**Comment by geerlingguy** [comment]
@N6REJ - I haven't tried doing anything with this on a PC; AFAICT, it's (a) not kosher with Apple's license agreement, and (b) a lot more difficult to try to get all the settings to work—it would probably have to be done on a Hackintosh. I can't imagine trying to build this from within Windows or Linux as the host OS.

**Comment by N6REJ** [comment]
@geerlingguy why is it against apples license, I dont' understand.

**Comment by syntaxerror** [comment]
@N6REJ look at t.ex. https://store.apple.com/Catalog/US/Images/MacOSX.htm
> 2. Permitted License Uses and Restrictions.
A. This License allows you to install and use one copy of the Apple Software on **a single Apple-labeled computer** at a time.

**Comment by N6REJ** [comment]
oh wow,.. k, ty.

**Comment by geerlingguy** [comment]
@N6REJ - That's not to say, of course, that many people go that route. It's just not _technically_ allowed by the license. And IMO it's not worth it (to me, at least) to try to maintain any instructions for non-Apple-hardware, since there's so much variation in both individual hardware rigs and ability to debug/troubleshoot specific issues.
