### ISSUE TITLE
virtualize installed copy

### ISSUE THREAD

**Issue by drocsid** [geerlingguy/macos-virtualbox-vm#43]
I had a friend run the installed copy of windows inside a VM from linux running on the same machine. I see some value in this. Have you tried this and if so it might be nice to provide an example.

**Comment by geerlingguy** [comment]
I'm not quite sure what's being asked here; are you saying can you run windows inside VirtualBox? Or macOS on Linux?

**Comment by ts-toh** [comment]
@geerlingguy what I believe he is asking is if you can you run as a vm, an installed non-virtualized os in another partition. VMWare Fusion lets you boot windows or linux directly from your bootcamp partition, so that if you need to run something from it, you don't have to actually reboot.

The answer is probably, but it might not be simple. I have done this with everything but OSX. It usually involves manually creating a special vmdk file that points to the physical partition, and remaps certain values for the VM.

If you don't need to have two boot entry points for your OSX installation though, OSX is way easier to virtualize. Just start VirtualBox, and instead of installing, just use Disk Utility to Restore from the system you want to virtualize. I do it with all of my old OSX machines.

**Comment by geerlingguy** [comment]
Ah yeah... doing that with macOS may be nigh impossible. And I definitely don't think I'd have the inclination to support that usage pattern in this project.
