### ISSUE TITLE
Hangs during initial boot - Yosemite and VB 5.2.4 on Linux

### ISSUE THREAD

**Issue by jonathankonrad** [geerlingguy/macos-virtualbox-vm#47]
This looks like excellent work! Thank you. I used my mac to download Yosemite, then your script to create an ISO then moved it to my Linux Box and tried to create the VM. Everything worked like it should, including setting the CPU parameters. However, when I try to boot for the first time, this is where it hangs. Should this work on Linux?
![yosemite_vm](https://user-images.githubusercontent.com/451444/34894347-41b57564-f79e-11e7-9de5-41a74e5070a0.png)

**Comment by geerlingguy** [comment]
It looks like the issue is the CPU model the VM is seeing. Unfortunately, I can't provide support for running ISOs generated with this project outside a macOS environment since it's not allowed in the macOS EULA from Apple. There are some other forums where you might be able to find more help though (reddit / hackintosh communities).
